# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
